//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travelia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookinginfo
    {
        public int id { get; set; }
        public string travellermail { get; set; }
        public string hotelempmail { get; set; }
        public string hotelname { get; set; }
        public string checkin { get; set; }
        public string checkout { get; set; }
        public string days { get; set; }
        public string roomtype { get; set; }
        public string totalcost { get; set; }
        public string status { get; set; }
    }
}
