//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travelia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotelinfo
    {
        public int id { get; set; }
        public string hotelempmail { get; set; }
        public string hotelname { get; set; }
        public string division { get; set; }
        public string location { get; set; }
        public string totalroom { get; set; }
        public string roomtypes { get; set; }
        public string description { get; set; }
        public string pictures { get; set; }
        public string status { get; set; }
    }
}
