//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travelia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salarysheet
    {
        public int id { get; set; }
        public string custcaremail { get; set; }
        public string salarypaid { get; set; }
        public string paidmonth { get; set; }
    }
}
